### PR TITLE
Update callers-zips.json

### PR DESCRIPTION
**Pull request by ldonforth**
January 2020 update

### CODE REVIEW

**Comment by jeffkaufman** [comment]
Looks good; merged!

**Comment by jeffkaufman** [comment]
https://www.trycontra.com/callers-heatmap confirmed working with the change

**Comment by ldonforth** [comment]
Nice.

Someday I might build out making that click-through like your dance map
with links; but not any time soon.

Take care,

**Comment by jeffkaufman** [comment]
If you wanted to give me something in the format `{"zip": ["link1", "link2"]}` I could do the rest

**Comment by ldonforth** [comment]
Only ~1/2 of folks list a website.
I could give you a list {"zip": ["mailto:email@address"]} since almost
everyone submitted an e-mail address.
Or I could give a mailto and a web address for the folks that provide both.

Is it better to give a consistent format of the lowest common denominator?
Or is it easy enough to code multiple links for the same person?

There are ~6 pairs, where two people list the same zip code. Can I pass you
{"zip": ["Name", "mailto:email@address" <, "website">]}
so folks would know who they're e-mailing?
Or would you want one listing for the zip, and every link pertinent to that
zip code?

**Comment by jeffkaufman** [comment]
How about:

```
{"zip": [
   {
     "name": "Pat Smith",
     "email": "pat.smith@example",
     "website": "https://pat.smith.example"
   },
   {
     "name": "Sam Jones",
     "email": "sam.jones@example",
     "website": "https://sam.jones.example"
   }
]}

If a key wasn't present for someone you could leave it off:

```
   {
     "name": "Sam Jones",
     "email": "sam.jones@example",
   }
```

Then I could make it so when someone clicked on a pin it would pop up a list of names with various contact methods?

**Comment by ldonforth** [comment]
Would it work if I gave you every entry on a separate line?

It's pretty easy for me to pass you:
{"zip": "04038", [{"name": "Shari Shakti", "email": "armswideopen1@gmail.com"
}]}
{"zip": "04101", [{"name": "Dela Murphy", "email": "Dela@delahere.com",
"website": "Delahere.com"}]}

{"zip": "04101", [{"name": "Dugan Murphy", "email": "dugan@duganmurphy.com",
"website": "http://www.duganmurphy.com"}]}
{"zip": "04680", [{"name": "Allison Aldrich Smith", "email": "
huntandallison@gmail.com", "website": "www.huntandallison.net"}]}
and have that be something the spreadsheet automatically generates.

I can probably figure out a way to get the same zipcode entries to
concatenate; but I'm currently looking at either doing it by hand making a
spreadsheet kludge.

Thoughts?

**Comment by jeffkaufman** [comment]
If you want separate lines, how about:

```
[
{ "zip": "12345", "name": "Pat Smith", "email": "pat.smith@example", "website": "https://pat.smith.example" },
{ "zip": "67890", "name": "Sam Jones", "email": "sam.jones@example", "website": "https://sam.jones.example"}
]
```

**Comment by ldonforth** [comment]
Sure, that's pretty easy.

Want to make a dummy document and have me open a pull request? Or want me
to make a document and have you feed off it?

**Comment by jeffkaufman** [comment]
Why don't you make one, make a PR, and then I'll write the code that interprets it?

**Comment by ldonforth** [comment]
Alright, if I did it correctly, you should have a pull request for
caller-links.json

Let me know if that works; if you need formatting tweaks, etc. No rush to
create this, but I thought it'd be nice.

**Comment by jeffkaufman** [comment]
Your PR #16 looked good, and I merged it.  I'll work on making the site use it at some point!

**Pull request merged**
